-- Insert real organizations from the provided data (fixed version)
-- Government Partners
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Ministry of Economic Affairs', 'Government ministry overseeing economic development, trade, and industry policies in Bhutan', 'government', '{"Government", "Policy", "Economic Development"}', '{"Industrial Development", "Trade Policy", "Economic Planning"}', '{"Businesses", "Investors", "Entrepreneurs"}', 'Thimphu', 'https://www.moea.gov.bt', 2008),
('Department of Industry', 'Government department responsible for industrial licensing, business registration, and FDI facilitation', 'government', '{"Industry", "Licensing", "FDI"}', '{"Business Registration", "Industrial Licensing", "FDI Facilitation"}', '{"Startups", "SMEs", "Foreign Investors"}', 'Thimphu', 'https://www.doi.gov.bt', 2010),
('Druk Holding & Investments', 'Government-owned sovereign wealth fund investing in strategic sectors and supporting private sector development', 'government', '{"Investment", "Sovereign Fund", "Strategic Development"}', '{"Strategic Investments", "Corporate Governance", "Capacity Building"}', '{"Large Enterprises", "Growth Stage Companies"}', 'Thimphu', 'https://www.dhi.bt', 2007),
('Export Import Bank of India', 'Financial institution supporting trade finance and development projects in Bhutan', 'government', '{"Banking", "Trade Finance", "Development"}', '{"Trade Finance", "Project Financing", "Credit Facilities"}', '{"Exporters", "Importers", "Large Projects"}', 'New Delhi', 'https://www.eximbankindia.in', 1982),
('UNDP Bhutan', 'United Nations Development Programme supporting sustainable development and innovation in Bhutan', 'government', '{"UN", "Development", "Sustainability", "Innovation"}', '{"SDG Implementation", "Innovation Labs", "Capacity Building"}', '{"Government", "NGOs", "Social Entrepreneurs"}', 'Thimphu', 'https://www.undp.org/bhutan', 1973);

-- Events & Communities  
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, established) VALUES
('Startup Weekend Bhutan', 'Annual 54-hour entrepreneurship event bringing together developers, designers, and business minds', 'events', '{"Events", "Hackathon", "Networking", "Entrepreneurship"}', '{"Startup Weekend", "Pitch Competitions", "Networking Events"}', '{"Aspiring Entrepreneurs", "Students", "Developers", "Designers"}', 'Thimphu', 2015),
('TEDx Thimphu', 'Platform for sharing innovative ideas and inspiring talks in Bhutan', 'events', '{"TED", "Ideas", "Innovation", "Speaking"}', '{"TEDx Events", "Speaker Development", "Community Building"}', '{"Thought Leaders", "Innovators", "General Public"}', 'Thimphu', 2012),
('Dragon Chamber', 'Business networking and advocacy organization for private sector development', 'events', '{"Business", "Networking", "Advocacy", "Private Sector"}', '{"Business Networking", "Policy Advocacy", "Trade Promotion"}', '{"Business Owners", "Entrepreneurs", "Professionals"}', 'Thimphu', 2019),
('Young Entrepreneurs Association', 'Association supporting young entrepreneurs and startup ecosystem development', 'events', '{"Youth", "Entrepreneurs", "Association", "Support"}', '{"Mentorship Programs", "Networking Events", "Skill Development"}', '{"Young Entrepreneurs", "Students", "Recent Graduates"}', 'Thimphu', 2016);

-- Media
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Business Bhutan', 'Leading business publication covering startup stories and economic development', 'media', '{"Media", "Business News", "Publications"}', '{"Business Coverage", "Startup Stories", "Economic Analysis"}', '{"Entrepreneurs", "Investors", "Business Community"}', 'Thimphu', 'https://www.businessbhutan.bt', 2008),
('The Bhutanese', 'Independent newspaper covering business, politics, and social issues', 'media', '{"Newspaper", "Independent Media", "Current Affairs"}', '{"News Coverage", "Investigative Journalism", "Business Reporting"}', '{"General Public", "Business Community", "Policy Makers"}', 'Thimphu', 'https://www.thebhutanese.bt', 2012),
('Kuensel Corporation', 'National newspaper of Bhutan covering comprehensive news including business and entrepreneurship', 'media', '{"National Media", "Newspaper", "Government Media"}', '{"News Publishing", "Business Coverage", "Public Information"}', '{"General Public", "Government", "Business Community"}', 'Thimphu', 'https://www.kuenselonline.com', 1967),
('BBS Broadcasting', 'National broadcaster providing news and information services', 'media', '{"Broadcasting", "Television", "Radio", "National Media"}', '{"News Broadcasting", "Documentary Production", "Public Service"}', '{"General Public", "Government", "International Audience"}', 'Thimphu', 'https://www.bbs.bt', 1973),
('Drukpa Publications', 'Publishing house focusing on Bhutanese literature and business content', 'media', '{"Publishing", "Literature", "Business Content"}', '{"Book Publishing", "Content Creation", "Literary Promotion"}', '{"Authors", "Readers", "Educational Institutions"}', 'Thimphu', 'https://www.drukpa.bt', 2010);