-- Continue adding more categories
-- Incubators & Accelerators
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Loden Foundation', 'Non-profit supporting entrepreneurship through education, mentorship, and micro-financing', 'incubators', '{"Non-profit", "Entrepreneurship", "Education", "Microfinance"}', '{"Entrepreneurship Education", "Mentorship Programs", "Micro-lending"}', '{"Rural Entrepreneurs", "Youth", "Women", "Social Entrepreneurs"}', 'Thimphu', 'https://www.lodenfoundation.org', 2009),
('Bhutan Innovation Hub', 'Government initiative supporting technology innovation and startup development', 'incubators', '{"Government", "Technology", "Innovation", "Incubation"}', '{"Technology Incubation", "Innovation Support", "R&D Facilitation"}', '{"Tech Startups", "Innovators", "Researchers"}', 'Thimphu', 'https://www.innovationhub.bt', 2020),
('JICA Innovation Center', 'Japan International Cooperation Agency supporting innovation and entrepreneurship', 'incubators', '{"International", "Japan", "Innovation", "Development"}', '{"Innovation Programs", "Technical Assistance", "Capacity Building"}', '{"Entrepreneurs", "Innovators", "Government"}', 'Thimphu', 'https://www.jica.go.jp', 2019);

-- Investors & VC
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Bhutan Development Bank', 'Development financial institution supporting SMEs and entrepreneurship', 'investors', '{"Development Finance", "Banking", "SME Support"}', '{"SME Lending", "Entrepreneurship Loans", "Development Finance"}', '{"SMEs", "Entrepreneurs", "Rural Businesses"}', 'Thimphu', 'https://www.bdb.bt', 1988),
('Bank of Bhutan', 'Commercial bank providing business and entrepreneurship financing', 'investors', '{"Commercial Bank", "Business Finance", "Lending"}', '{"Business Loans", "Trade Finance", "Working Capital"}', '{"Businesses", "Entrepreneurs", "Traders"}', 'Thimphu', 'https://www.bob.bt', 1968),
('Druk PNB Bank', 'Commercial bank offering business financing and investment services', 'investors', '{"Commercial Bank", "Investment", "Business Finance"}', '{"Business Lending", "Investment Services", "Trade Finance"}', '{"Businesses", "Investors", "Entrepreneurs"}', 'Thimphu', 'https://www.drukpnbbank.bt', 2010),
('RICBL Insurance', 'Insurance company providing business and investment products', 'investors', '{"Insurance", "Investment", "Risk Management"}', '{"Business Insurance", "Investment Products", "Risk Coverage"}', '{"Businesses", "Entrepreneurs", "Investors"}', 'Thimphu', 'https://www.ricbl.bt', 1975);

-- Education
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Royal University of Bhutan', 'National university system offering entrepreneurship and business programs', 'education', '{"University", "Higher Education", "Research"}', '{"Degree Programs", "Research", "Innovation Labs", "Entrepreneurship Courses"}', '{"Students", "Researchers", "Faculty"}', 'Thimphu', 'https://www.rub.edu.bt', 2003),
('College of Science and Technology', 'Engineering and technology college under RUB focusing on innovation', 'education', '{"Engineering", "Technology", "Innovation", "College"}', '{"Engineering Programs", "Technology Development", "Innovation Projects"}', '{"Engineering Students", "Technology Professionals"}', 'Rinchending', 'https://www.cst.edu.bt', 2001),
('Jigme Namgyel Engineering College', 'Engineering college offering technology and innovation programs', 'education', '{"Engineering", "Technology", "Innovation"}', '{"Engineering Education", "Technology Programs", "Innovation Labs"}', '{"Engineering Students", "Technology Enthusiasts"}', 'Dewathang', 'https://www.jnec.edu.bt', 1972),
('Gaeddu College of Business', 'Business college offering entrepreneurship and management programs', 'education', '{"Business", "Management", "Entrepreneurship"}', '{"Business Programs", "Entrepreneurship Courses", "Management Education"}', '{"Business Students", "Aspiring Entrepreneurs"}', 'Gedu', 'https://www.gcbs.edu.bt', 2009);

-- Training & Mentorship
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Bhutan Chamber of Commerce', 'Peak private sector organization providing training and business support', 'training', '{"Training", "Mentorship", "Business Support", "Chamber"}', '{"Business Training", "Export Assistance", "Networking", "Skills Development"}', '{"SMEs", "Exporters", "New Businesses", "Entrepreneurs"}', 'Thimphu', 'https://www.bcci.org.bt', 1980),
('Institute of Management Studies', 'Management training institute offering business and leadership programs', 'training', '{"Management", "Training", "Leadership", "Professional Development"}', '{"Management Training", "Leadership Development", "Professional Courses"}', '{"Managers", "Executives", "Professionals"}', 'Thimphu', 'https://www.ims.edu.bt', 1995),
('Skills Development Corporation', 'Government corporation providing vocational and entrepreneurship training', 'training', '{"Skills", "Vocational Training", "Government", "Development"}', '{"Vocational Training", "Skills Development", "Entrepreneurship Training"}', '{"Job Seekers", "Entrepreneurs", "Youth"}', 'Thimphu', 'https://www.sdc.gov.bt', 2010);