-- Add more organizations from the provided spreadsheet data
-- Government Partners (continued)
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, email, established) VALUES
('Gelephu Mindfulness City Authority', 'Leading domestic implementation of $100 billion smart city project with integrated digital asset strategy', 'government', '{"Government", "Smart City", "Digital Assets", "Urban Development"}', '{"Smart City Development", "Digital Infrastructure", "Urban Planning"}', '{"Citizens", "Businesses", "International Investors"}', 'Gelephu', 'https://gmc.bt', 'contact@gmc.bt', 2023),
('Bhutan National Digital Identity', 'World first sovereign self-sovereign identity system built on blockchain using CREDIBLE protocol', 'government', '{"Digital Identity", "Blockchain", "Sovereignty", "CREDIBLE"}', '{"Digital Identity Platform", "Blockchain Implementation", "Citizen Services"}', '{"Citizens", "Government Agencies", "International Partners"}', 'Thimphu', 'https://ndi.gov.bt', 'support@ndi.gov.bt', 2021),
('GovTech Bhutan', 'Leading white-label government digital transformation solutions with blockchain governance', 'government', '{"GovTech", "Digital Transformation", "Blockchain"}', '{"Digital Government Solutions", "Blockchain Governance", "Technology Implementation"}', '{"Government", "Public Sector", "Citizens"}', 'Thimphu', 'https://gt.gov.bt', 'contact@govtech.bt', 2020),
('Royal Monetary Authority', 'Central bank partnered with Ripple for Digital Ngultrum (CBDC) development', 'government', '{"Central Bank", "CBDC", "Digital Currency", "Ripple"}', '{"Digital Currency Development", "Monetary Policy", "Financial Regulation"}', '{"Financial Institutions", "Citizens", "Businesses"}', 'Thimphu', 'https://www.rma.org.bt', 'contact@rma.org.bt', 1982),
('Ministry of Industry Commerce', 'Government ministry overseeing industrial and commercial development', 'government', '{"Ministry", "Industry", "Commerce", "Trade"}', '{"Industrial Development", "Trade Promotion", "Commercial Policy"}', '{"Industries", "Traders", "Entrepreneurs"}', 'Thimphu', 'https://www.moic.gov.bt', 'contact@moic.gov.bt', 2008);

-- Financial Institutions & Investors (continued)
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('ORO Bank', 'Asia first full reserve digital bank serving GMC and global Web3 startups and DAOs', 'investors', '{"Digital Bank", "Web3", "Full Reserve", "Cryptocurrency"}', '{"Digital Banking", "Web3 Services", "Cryptocurrency Banking"}', '{"Web3 Startups", "DAOs", "Cryptocurrency Businesses"}', 'Thimphu', 'https://oro.bank', 1988),
('Bitdeer Technologies', 'Leading crypto mining company with operations in Bhutan', 'investors', '{"Cryptocurrency", "Mining", "Blockchain", "Technology"}', '{"Crypto Mining", "Blockchain Infrastructure", "Digital Assets"}', '{"Crypto Investors", "Blockchain Companies", "Tech Startups"}', 'Thimphu', 'https://www.bitdeer.com', 2021),
('Matrixport', 'First financial services permission license applicant in GMC offering structured products', 'investors', '{"Financial Services", "Structured Products", "Digital Assets"}', '{"Digital Asset Services", "Financial Products", "Investment Solutions"}', '{"Institutional Investors", "High Net Worth", "Crypto Traders"}', 'Gelephu', 'https://www.matrixport.com', 2019),
('500 Global', 'Part of Greater Bhutan entrepreneurship Corridor initiative with international presence', 'investors', '{"Venture Capital", "International", "Entrepreneurship", "Accelerator"}', '{"Startup Investment", "Acceleration Programs", "Global Expansion"}', '{"Startups", "Entrepreneurs", "International Ventures"}', 'Thimphu', 'https://500.co', 2010),
('Ripple Labs', 'Partnered with RMA for Digital Ngultrum (CBDC) development for traditional finance Web3 integration', 'investors', '{"Blockchain", "CBDC", "Digital Payments", "Fintech"}', '{"CBDC Development", "Cross-border Payments", "Blockchain Solutions"}', '{"Central Banks", "Financial Institutions", "Government"}', 'San Francisco', 'https://ripple.com', 2012);

-- Incubators & Accelerators (continued)
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Forest eco-preneur (Loden Foundation)', 'Supporting eco-preneurs and social entrepreneurs with potential for blockchain-based impact measurement', 'incubators', '{"Eco-preneurship", "Social Impact", "Environmental", "Blockchain"}', '{"Environmental Entrepreneurship", "Impact Measurement", "Sustainable Business"}', '{"Environmental Entrepreneurs", "Social Innovators", "Impact Investors"}', 'Thimphu', 'https://www.loden.org', 2009),
('SprintBoard (UNDP + Loden + MoICE)', 'Multi-partner accelerator program with government and international development backing', 'incubators', '{"Multi-partner", "Government", "International", "Accelerator"}', '{"Startup Acceleration", "Government Partnerships", "International Development"}', '{"Startups", "Social Entrepreneurs", "Government Partners"}', 'Thimphu', 'https://www.sprintboard.bt', 2020),
('RUB Innovation Incubator', 'University-based incubation programs across RUB colleges for education-focused entrepreneurship', 'incubators', '{"University", "Education", "Innovation", "Academic"}', '{"University Incubation", "Academic Entrepreneurship", "Student Innovation"}', '{"University Students", "Faculty", "Academic Entrepreneurs"}', 'Thimphu', 'https://www.rub.edu.bt', 2018),
('Bhutan Innovation and Technology Centre', 'Technology incubator previously directed by Dr. Tshering Cigay Dorji', 'incubators', '{"Technology", "Innovation", "Government", "R&D"}', '{"Technology Incubation", "R&D Support", "Innovation Facilitation"}', '{"Tech Entrepreneurs", "Researchers", "Innovators"}', 'Thimphu', 'https://bitc.gov.bt', 2019),
('Royal Foundation Programme', 'New acceleration program with 15+ lab incubators providing royal backing for startups', 'incubators', '{"Royal", "Acceleration", "Lab Incubators", "Government Support"}', '{"Royal Acceleration", "Lab Incubation", "Startup Support"}', '{"High-potential Startups", "Innovation Labs", "Tech Entrepreneurs"}', 'Thimphu', 'https://royalfoundation.bt', 2023);

-- Education Institutions (continued)
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Thimphu TechPark Limited', 'Hub for 700+ employees across 75+ international companies suitable for blockchain platforms and DeFi analytics', 'infrastructure', '{"TechPark", "International", "Blockchain", "DeFi"}', '{"Technology Hub", "Blockchain Infrastructure", "DeFi Analytics"}', '{"Tech Companies", "Blockchain Startups", "International Businesses"}', 'Thimphu', 'https://thimphutechpark.bt', 2015),
('Innovate Bhutan', 'Only co-working space in Bhutan for FDI companies including blockchain and Web3 services', 'infrastructure', '{"Co-working", "FDI", "Blockchain", "Web3"}', '{"Co-working Space", "FDI Support", "Blockchain Services"}', '{"FDI Companies", "Blockchain Startups", "Web3 Developers"}', 'Thimphu', 'https://innovate.bt', 2018),
('IT Park (Government)', 'Government-provided industrial space at subsidized rates for IT companies', 'infrastructure', '{"Government", "IT Park", "Subsidized", "Industrial Space"}', '{"IT Infrastructure", "Government Support", "Industrial Development"}', '{"IT Companies", "Tech Startups", "Software Developers"}', 'Thimphu', 'https://itpark.gov.bt', 2016),
('NofikiNation', 'Bhutan AI startup with major institutional clients including Bhutan NDI and decentralized AI networks', 'startups', '{"AI", "Institutional", "Decentralized", "Technology"}', '{"AI Solutions", "Institutional Services", "Decentralized Networks"}', '{"Government", "Institutions", "Enterprise Clients"}', 'Thimphu', 'https://nofikinaton.bt', 2020),
('DrukSat/MyDrukRide', 'Multi-service platform with high Web3 potential for cryptocurrency payments and decentralized protocols', 'startups', '{"Multi-service", "Web3", "Cryptocurrency", "Decentralized"}', '{"Multi-service Platform", "Crypto Payments", "Decentralized Services"}', '{"Consumers", "Crypto Users", "Web3 Enthusiasts"}', 'Thimphu', 'https://www.drukride.com', 2019);