-- Add more comprehensive organizations from all categories
-- Additional Government Partners
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('CSI Market', 'Government-backed market for local products with potential for blockchain-based feature verification', 'policy', '{"Government", "Market", "Local Products", "Blockchain"}', '{"Market Development", "Local Product Promotion", "Verification Systems"}', '{"Local Producers", "Consumers", "Government"}', 'Thimphu', 'https://csi.gov.bt', 2018),
('Department of Tourism', 'Tourism promotion and market access for blockchain-based tourism services', 'policy', '{"Tourism", "Government", "Market Access", "Blockchain"}', '{"Tourism Promotion", "Market Access", "Digital Tourism Services"}', '{"Tourism Businesses", "Travelers", "Service Providers"}', 'Thimphu', 'https://tourism.gov.bt', 1974),
('FDI Policy', 'Foreign Direct Investment policy promotion in IT industry with 100% ownership for qualifying investments', 'policy', '{"FDI", "IT Industry", "Investment Policy", "100% Ownership"}', '{"FDI Promotion", "Investment Facilitation", "IT Development"}', '{"Foreign Investors", "IT Companies", "International Businesses"}', 'Thimphu', 'https://fdi.gov.bt', 2010),
('Economic Stimulus Program', 'Government-funded economic stimulus focusing on small and cottage industry funded by Government of India', 'policy', '{"Economic Stimulus", "Small Industry", "Government", "India"}', '{"Economic Development", "Small Business Support", "Funding Programs"}', '{"Small Businesses", "Cottage Industries", "Entrepreneurs"}', 'Thimphu', 'https://stimulus.gov.bt', 2020),
('ToT on Small Business Counseling and Coaching', 'Training of Trainers program for business counseling and government capacity building', 'training', '{"Training of Trainers", "Business Counseling", "Government", "Capacity Building"}', '{"ToT Programs", "Business Counseling", "Capacity Building"}', '{"Trainers", "Government Officials", "Business Counselors"}', 'Thimphu', 'https://sme.gov.bt', 2019);

-- More Education Institutions
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Gyalpoizhing College of Information Technology', 'Specialized IT education with part of RUB system', 'education', '{"IT Education", "RUB", "Technology", "Specialized"}', '{"IT Programs", "Technology Education", "Specialized Training"}', '{"IT Students", "Technology Professionals", "Engineers"}', 'Gyalpoizhing', 'https://www.gcit.edu.bt', 2003),
('College of Science and Technology', 'Science and technology education as part of RUB system', 'education', '{"Science", "Technology", "RUB", "Engineering"}', '{"Science Programs", "Technology Education", "Engineering Courses"}', '{"Science Students", "Engineers", "Technology Professionals"}', 'Rinchending', 'https://www.cst.edu.bt', 2001),
('Samtse College of Education', 'Teacher education and training as part of RUB system', 'education', '{"Teacher Education", "Training", "RUB", "Education"}', '{"Teacher Training", "Education Programs", "Professional Development"}', '{"Teachers", "Education Professionals", "Students"}', 'Samtse', 'https://www.sce.edu.bt', 1992),
('Institute Management Studies', 'Specialized institute for happiness studies with potential for blockchain-based wellness tracking', 'education', '{"Management", "Happiness Studies", "Wellness", "Blockchain"}', '{"Management Education", "Happiness Research", "Wellness Programs"}', '{"Managers", "Researchers", "Wellness Professionals"}', 'Thimphu', 'https://www.ims.edu.bt', 1995),
('National Museum of Bhutan', 'National cultural institution with potential for blockchain-based heritage preservation', 'miscellaneous', '{"Cultural", "Museum", "Heritage", "Blockchain"}', '{"Cultural Preservation", "Heritage Education", "Museum Services"}', '{"Visitors", "Cultural Enthusiasts", "Researchers"}', 'Paro', 'https://museum.gov.bt', 1968);

-- Technology Startups and SMEs
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Sooryaala', 'Local tech startup with details available through direct contact', 'startups', '{"Technology", "Local", "Startup"}', '{"Tech Solutions", "Local Services", "Software Development"}', '{"Local Businesses", "Tech Community", "Consumers"}', 'Thimphu', 'contact@sooryaala.bt', 2019),
('Booknese', 'Local tech startup with details available through direct contact', 'startups', '{"Technology", "Books", "Digital Platform"}', '{"Digital Platform", "Book Services", "Educational Technology"}', '{"Readers", "Students", "Educational Institutions"}', 'Thimphu', 'contact@booknese.bt', 2020),
('DrukSmart', 'Local tech startup with details available through direct contact', 'startups', '{"Smart Solutions", "Technology", "Local"}', '{"Smart Solutions", "Technology Services", "Local Innovation"}', '{"Businesses", "Government", "Tech Community"}', 'Thimphu', 'contact@druksmart.bt', 2018),
('MultiPlatform Corporation', 'Technology corporation with Bhutan operations', 'startups', '{"Technology", "Corporation", "Multi-platform"}', '{"Multi-platform Solutions", "Technology Services", "Corporate Solutions"}', '{"Enterprises", "Government", "Large Organizations"}', 'Thimphu', 'contact@multiplatform.bt', 2017),
('Southtech Bhutan', 'International technology services company with Bhutan operations', 'startups', '{"International", "Technology Services", "Bhutan Operations"}', '{"Technology Services", "International Solutions", "IT Support"}', '{"International Clients", "Technology Companies", "Businesses"}', 'Thimphu', 'contact@southtech.bt', 2016);

-- Policy and Access Organizations  
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('ToT on Business Incubation Management', 'Training of Trainers for business incubation management and government capacity building', 'training', '{"Training of Trainers", "Business Incubation", "Management", "Government"}', '{"ToT Programs", "Business Incubation Training", "Management Development"}', '{"Trainers", "Incubation Managers", "Government Officials"}', 'Thimphu', 'contact@incubation.gov.bt', 2018),
('Spirit (Bhutan)', 'Innovation spirit and technology training for local business innovation focus', 'training', '{"Innovation", "Technology Training", "Local Business", "Spirit"}', '{"Innovation Training", "Technology Development", "Business Innovation"}', '{"Local Businesses", "Innovators", "Entrepreneurs"}', 'Thimphu', 'contact@spirit.bt', 2019),
('Kids MBA (Bhutan)', 'MBA program for children and early entrepreneurship education', 'education', '{"Kids", "MBA", "Early Education", "Entrepreneurship"}', '{"Kids MBA Program", "Early Entrepreneurship", "Business Education"}', '{"Children", "Young Students", "Future Entrepreneurs"}', 'Thimphu', 'contact@kidsmba.bt', 2020),
('Innovation Sprint (Bhutan)', 'Innovation spirit and technology training for local business innovation focus', 'training', '{"Innovation Sprint", "Technology", "Training", "Business"}', '{"Innovation Programs", "Sprint Training", "Technology Development"}', '{"Innovators", "Tech Professionals", "Entrepreneurs"}', 'Thimphu', 'contact@innovationsprint.bt', 2021),
('New Business Creation (Tarayana)', 'New business creation program by Tarayana Foundation for social impact entrepreneurship', 'training', '{"New Business", "Social Impact", "Tarayana", "Entrepreneurship"}', '{"Business Creation", "Social Entrepreneurship", "Impact Programs"}', '{"Social Entrepreneurs", "Community Leaders", "Impact Investors"}', 'Thimphu', 'https://tarayana.org', 2017);