-- Insert real organizations from the provided data
-- Government Partners
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Ministry of Economic Affairs', 'Government ministry overseeing economic development, trade, and industry policies in Bhutan', 'government', '{"Government", "Policy", "Economic Development"}', '{"Industrial Development", "Trade Policy", "Economic Planning"}', '{"Businesses", "Investors", "Entrepreneurs"}', 'Thimphu', 'https://www.moea.gov.bt', 2008),
('Department of Industry', 'Government department responsible for industrial licensing, business registration, and FDI facilitation', 'government', '{"Industry", "Licensing", "FDI"}', '{"Business Registration", "Industrial Licensing", "FDI Facilitation"}', '{"Startups", "SMEs", "Foreign Investors"}', 'Thimphu', 'https://www.doi.gov.bt', 2010),
('Druk Holding & Investments', 'Government-owned sovereign wealth fund investing in strategic sectors and supporting private sector development', 'government', '{"Investment", "Sovereign Fund", "Strategic Development"}', '{"Strategic Investments", "Corporate Governance", "Capacity Building"}', '{"Large Enterprises", "Growth Stage Companies"}', 'Thimphu', 'https://www.dhi.bt', 2007),
('Export Import Bank of India (EXIM Bank)', 'Financial institution supporting trade finance and development projects in Bhutan', 'government', '{"Banking", "Trade Finance", "Development"}', '{"Trade Finance", "Project Financing", "Credit Facilities"}', '{"Exporters", "Importers", "Large Projects"}', 'New Delhi', 'https://www.eximbankindia.in', 1982),
('UNDP Bhutan', 'United Nations Development Programme supporting sustainable development and innovation in Bhutan', 'government', '{"UN", "Development", "Sustainability", "Innovation"}', '{"SDG Implementation", "Innovation Labs", "Capacity Building"}', '{"Government", "NGOs", "Social Entrepreneurs"}', 'Thimphu', 'https://www.undp.org/bhutan', 1973);

-- Events & Communities
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, established) VALUES
('Startup Weekend Bhutan', 'Annual 54-hour entrepreneurship event bringing together developers, designers, and business minds', 'events', '{"Events", "Hackathon", "Networking", "Entrepreneurship"}', '{"Startup Weekend", "Pitch Competitions", "Networking Events"}', '{"Aspiring Entrepreneurs", "Students", "Developers", "Designers"}', 'Thimphu', 2015),
('TEDx Thimphu', 'Platform for sharing innovative ideas and inspiring talks in Bhutan', 'events', '{"TED", "Ideas", "Innovation", "Speaking"}', '{"TEDx Events", "Speaker Development", "Community Building"}', '{"Thought Leaders", "Innovators", "General Public"}', 'Thimphu', 2012),
('Bhutan Innovation and Entrepreneurship Summit', 'Annual summit bringing together entrepreneurs, investors, and ecosystem players', 'events', '{"Summit", "Innovation", "Entrepreneurship", "Networking"}', '{"Annual Summit", "Panel Discussions", "Networking Sessions"}', '{"Entrepreneurs", "Investors", "Policymakers"}', 'Thimphu', 2018),
('Dragon Chamber', 'Business networking and advocacy organization for private sector development', 'events', '{"Business", "Networking", "Advocacy", "Private Sector"}', '{"Business Networking", "Policy Advocacy", "Trade Promotion"}', '{"Business Owners", "Entrepreneurs", "Professionals"}', 'Thimphu', 2019),
('Young Entrepreneurs Association of Bhutan', 'Association supporting young entrepreneurs and startup ecosystem development', 'events', '{"Youth", "Entrepreneurs", "Association", "Support"}', '{"Mentorship Programs", "Networking Events", "Skill Development"}', '{"Young Entrepreneurs", "Students", "Recent Graduates"}', 'Thimphu', 2016);

-- Media
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Business Bhutan', 'Leading business publication covering startup stories and economic development', 'media', '{"Media", "Business News", "Publications"}', '{"Business Coverage", "Startup Stories", "Economic Analysis"}', '{"Entrepreneurs", "Investors", "Business Community"}', 'Thimphu', 'https://www.businessbhutan.bt', 2008),
('The Bhutanese', 'Independent newspaper covering business, politics, and social issues', 'media', '{"Newspaper", "Independent Media", "Current Affairs"}', '{"News Coverage", "Investigative Journalism", "Business Reporting"}', '{"General Public", "Business Community", "Policy Makers"}', 'Thimphu', 'https://www.thebhutanese.bt', 2012),
('Kuensel Corporation', 'National newspaper of Bhutan covering comprehensive news including business and entrepreneurship', 'media', '{"National Media", "Newspaper", "Government Media"}', '{"News Publishing", "Business Coverage", "Public Information"}', '{"General Public", "Government", "Business Community"}', 'Thimphu', 'https://www.kuenselonline.com', 1967),
('BBS (Bhutan Broadcasting Service)', 'National broadcaster providing news and information services', 'media', '{"Broadcasting", "Television", "Radio", "National Media"}', '{"News Broadcasting", "Documentary Production", "Public Service"}', '{"General Public", "Government", "International Audience"}', 'Thimphu', 'https://www.bbs.bt', 1973),
('Drukpa Publications', 'Publishing house focusing on Bhutanese literature and business content', 'media', '{"Publishing", "Literature", "Business Content"}', '{"Book Publishing", "Content Creation", "Literary Promotion"}', '{"Authors", "Readers", "Educational Institutions"}', 'Thimphu', 2010);

-- Incubators & Accelerators
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Loden Foundation', 'Non-profit supporting entrepreneurship through education, mentorship, and micro-financing', 'incubators', '{"Non-profit", "Entrepreneurship", "Education", "Microfinance"}', '{"Entrepreneurship Education", "Mentorship Programs", "Micro-lending", "Business Development"}', '{"Rural Entrepreneurs", "Youth", "Women", "Social Entrepreneurs"}', 'Thimphu', 'https://www.lodenfoundation.org', 2009),
('Bhutan Innovation and Technology Centre', 'Government initiative supporting technology innovation and startup development', 'incubators', '{"Government", "Technology", "Innovation", "Incubation"}', '{"Technology Incubation", "Innovation Support", "R&D Facilitation"}', '{"Tech Startups", "Innovators", "Researchers"}', 'Thimphu', 2020),
('JICA Bhutan Innovation Hub', 'Japan International Cooperation Agency supporting innovation and entrepreneurship', 'incubators', '{"International", "Japan", "Innovation", "Development"}', '{"Innovation Programs", "Technical Assistance", "Capacity Building"}', '{"Entrepreneurs", "Innovators", "Government"}', 'Thimphu', 2019),
('Startup Bhutan', 'Government initiative promoting startup ecosystem development', 'incubators', '{"Government", "Startup Ecosystem", "Promotion"}', '{"Startup Promotion", "Ecosystem Development", "Policy Support"}', '{"Startups", "Entrepreneurs", "Ecosystem Players"}', 'Thimphu', 2020),
('Innovation Lab Bhutan', 'Platform for innovation and technology development', 'incubators', '{"Innovation", "Technology", "Lab", "Development"}', '{"Innovation Projects", "Technology Development", "Prototyping"}', '{"Innovators", "Developers", "Researchers"}', 'Thimphu', 2018);

-- Investors & VC
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Bhutan Development Bank', 'Development financial institution supporting SMEs and entrepreneurship', 'investors', '{"Development Finance", "Banking", "SME Support"}', '{"SME Lending", "Entrepreneurship Loans", "Development Finance"}', '{"SMEs", "Entrepreneurs", "Rural Businesses"}', 'Thimphu', 'https://www.bdb.bt', 1988),
('Bank of Bhutan', 'Commercial bank providing business and entrepreneurship financing', 'investors', '{"Commercial Bank", "Business Finance", "Lending"}', '{"Business Loans", "Trade Finance", "Working Capital"}', '{"Businesses", "Entrepreneurs", "Traders"}', 'Thimphu', 'https://www.bob.bt', 1968),
('Druk PNB Bank', 'Commercial bank offering business financing and investment services', 'investors', '{"Commercial Bank", "Investment", "Business Finance"}', '{"Business Lending", "Investment Services", "Trade Finance"}', '{"Businesses", "Investors", "Entrepreneurs"}', 'Thimphu', 'https://www.drukpnbbank.bt', 2010),
('RICBL (Royal Insurance Corporation of Bhutan)', 'Insurance company providing business and investment products', 'investors', '{"Insurance", "Investment", "Risk Management"}', '{"Business Insurance", "Investment Products", "Risk Coverage"}', '{"Businesses", "Entrepreneurs", "Investors"}', 'Thimphu', 'https://www.ricbl.bt', 1975),
('Bhutan National Bank', 'State-owned bank providing development finance and business support', 'investors', '{"State Bank", "Development Finance", "Business Support"}', '{"Development Lending", "Business Finance", "Government Programs"}', '{"SMEs", "Government Projects", "Development Initiatives"}', 'Thimphu', 'https://www.bnb.bt', 1997);

-- Education
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Royal University of Bhutan', 'National university system offering entrepreneurship and business programs', 'education', '{"University", "Higher Education", "Research"}', '{"Degree Programs", "Research", "Innovation Labs", "Entrepreneurship Courses"}', '{"Students", "Researchers", "Faculty"}', 'Thimphu', 'https://www.rub.edu.bt', 2003),
('College of Science and Technology', 'Engineering and technology college under RUB focusing on innovation', 'education', '{"Engineering", "Technology", "Innovation", "College"}', '{"Engineering Programs", "Technology Development", "Innovation Projects"}', '{"Engineering Students", "Technology Professionals"}', 'Rinchending', 'https://www.cst.edu.bt', 2001),
('Jigme Namgyel Engineering College', 'Engineering college offering technology and innovation programs', 'education', '{"Engineering", "Technology", "Innovation"}', '{"Engineering Education", "Technology Programs", "Innovation Labs"}', '{"Engineering Students", "Technology Enthusiasts"}', 'Dewathang', 'https://www.jnec.edu.bt', 1972),
('College of Natural Resources', 'Agricultural and natural resources college promoting rural entrepreneurship', 'education', '{"Agriculture", "Natural Resources", "Rural Development"}', '{"Agricultural Programs", "Rural Entrepreneurship", "Natural Resource Management"}', '{"Agriculture Students", "Rural Entrepreneurs"}', 'Lobesa', 'https://www.cnr.edu.bt', 1992),
('Gaeddu College of Business Studies', 'Business college offering entrepreneurship and management programs', 'education', '{"Business", "Management", "Entrepreneurship"}', '{"Business Programs", "Entrepreneurship Courses", "Management Education"}', '{"Business Students", "Aspiring Entrepreneurs"}', 'Gedu', 'https://www.gcbs.edu.bt', 2009);

-- More organizations will be added in subsequent insertions due to query length limits