-- Add sample updates reflecting the comprehensive ecosystem
INSERT INTO public.updates (title, content, organization_name, published_date, is_featured) VALUES
('Gelephu Mindfulness City Authority Launches Digital Asset Strategy', 'GMC has announced the implementation of its comprehensive digital asset strategy as part of the $100 billion smart city project. The initiative will integrate blockchain technology for transparent governance and digital identity management.', 'Gelephu Mindfulness City Authority', '2024-07-07', true),
('ORO Bank Receives Digital Banking License', 'ORO Bank has officially received its digital banking license, making it Asia first full reserve digital bank. The bank will focus on serving Web3 startups, DAOs, and providing cryptocurrency banking services.', 'ORO Bank', '2024-07-05', true),
('Royal Foundation Programme Announces 15+ Lab Incubators', 'The Royal Foundation Programme has officially launched with over 15 lab incubators providing royal backing for high-potential startups. The program focuses on technology innovation and sustainable development.', 'Royal Foundation Programme', '2024-07-03', false),
('Thimphu TechPark Reaches 700+ Employees Milestone', 'Thimphu TechPark has reached a significant milestone with over 700 employees across 75+ international companies. The park continues to serve as a hub for blockchain platforms and DeFi analytics companies.', 'Thimphu TechPark Limited', '2024-07-01', false),
('Digital Ngultrum CBDC Development Progresses', 'The Royal Monetary Authority, in partnership with Ripple Labs, has announced significant progress in the development of Bhutan Digital Ngultrum (CBDC). The digital currency aims to integrate traditional finance with Web3 solutions.', 'Royal Monetary Authority', '2024-06-28', true),
('SprintBoard Multi-Partner Accelerator Opens Applications', 'The UNDP, Loden Foundation, and Ministry of Industry Commerce have opened applications for the SprintBoard accelerator program. The program offers government and international development backing for selected startups.', 'SprintBoard (UNDP + Loden + MoICE)', '2024-06-25', false),
('Bhutan National Digital Identity System Goes Live', 'The world first sovereign self-sovereign identity system built on blockchain using CREDIBLE protocol has officially gone live. Citizens can now access government services through secure blockchain-based digital identity.', 'Bhutan National Digital Identity', '2024-06-20', true),
('Friday Friends iBhutan Networking Event Series Expands', 'The popular Friday Friends networking event for tech and business community has expanded its reach, with regular events now supporting broader blockchain and Web3 community building across Thimphu.', 'Friday Friends (iBhutan)', '2024-06-18', false);