-- Add remaining categories and sample updates
-- Infrastructure
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Thimphu TechPark', 'Technology park providing infrastructure and business support for IT companies', 'infrastructure', '{"TechPark", "Co-working", "IT", "Infrastructure"}', '{"Co-working Spaces", "Business Incubation", "IT Services", "Office Space"}', '{"IT Companies", "Tech Startups", "Freelancers", "Digital Nomads"}', 'Thimphu', 'https://www.techpark.bt', 2015),
('Bhutan Business Hub', 'Business facility providing shared offices and meeting spaces for startups', 'infrastructure', '{"Business Hub", "Shared Office", "Meeting Spaces"}', '{"Shared Offices", "Meeting Rooms", "Business Support", "Networking"}', '{"Startups", "Small Businesses", "Consultants"}', 'Thimphu', 'https://www.businesshub.bt', 2018),
('Innovation Park Bhutan', 'Science and technology park promoting innovation and research', 'infrastructure', '{"Science Park", "Innovation", "Research", "Technology"}', '{"Research Facilities", "Innovation Labs", "Technology Development"}', '{"Researchers", "Tech Companies", "Innovators"}', 'Thimphu', 'https://www.innovationpark.bt', 2019);

-- Market Access
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Export Promotion Board', 'Government agency promoting Bhutanese exports and international trade', 'market', '{"Export", "Trade Promotion", "Government", "International"}', '{"Export Facilitation", "Market Research", "Trade Missions", "Branding"}', '{"Exporters", "Manufacturers", "Service Providers"}', 'Thimphu', 'https://www.epb.gov.bt', 2005),
('Trade Support Network', 'Organization facilitating market access and trade opportunities', 'market', '{"Trade", "Market Access", "Business Support"}', '{"Market Access", "Trade Support", "Business Matching"}', '{"Businesses", "Traders", "Exporters"}', 'Thimphu', 'https://www.tradesupport.bt', 2012),
('Bhutan Brand Initiative', 'Initiative promoting Brand Bhutan and premium positioning', 'market', '{"Branding", "Premium", "Marketing", "Positioning"}', '{"Brand Development", "Marketing Support", "Premium Positioning"}', '{"Businesses", "Exporters", "Tourism"}', 'Thimphu', 'https://www.brandbhutan.bt', 2014);

-- Startups & SMEs
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Drukair Digital', 'Aviation technology startup developing digital solutions', 'startups', '{"Aviation", "Digital", "Technology", "SaaS"}', '{"Digital Solutions", "Aviation Technology", "Customer Experience"}', '{"Aviation Industry", "Airlines", "Travelers"}', 'Paro', 'https://www.drukairdigital.com', 2020),
('Bhutan Telecom Digital', 'Digital services arm of national telecom providing tech solutions', 'startups', '{"Telecom", "Digital Services", "Technology"}', '{"Digital Services", "ICT Solutions", "Enterprise Services"}', '{"Businesses", "Government", "Consumers"}', 'Thimphu', 'https://www.bt.bt/digital', 2018),
('Mountain Hazelnuts', 'Agricultural venture promoting hazelnut farming and processing', 'startups', '{"Agriculture", "Processing", "Export", "Sustainable"}', '{"Farmer Training", "Processing", "Export Marketing"}', '{"Farmers", "Rural Communities", "International Buyers"}', 'Thimphu', 'https://www.mountainhazelnuts.com', 2009),
('Authentic Bhutan', 'Tourism startup offering authentic cultural experiences', 'startups', '{"Tourism", "Culture", "Authentic", "Experience"}', '{"Cultural Tours", "Authentic Experiences", "Sustainable Tourism"}', '{"Tourists", "Culture Enthusiasts", "Adventure Travelers"}', 'Thimphu', 'https://www.authenticbhutan.com', 2017);

-- Sample Updates
INSERT INTO public.updates (title, content, organization_name, published_date, is_featured) VALUES
('New Innovation Hub Opens in Thimphu', 'The Bhutan Innovation Hub has officially opened its doors in Thimphu, providing state-of-the-art facilities for tech startups and innovators. The facility includes co-working spaces, meeting rooms, and advanced technology infrastructure to support the growing startup ecosystem.', 'Bhutan Innovation Hub', '2024-01-15', true),
('Startup Weekend Bhutan 2024 Applications Open', 'Applications are now open for Startup Weekend Bhutan 2024! Join us for 54 hours of innovation, collaboration, and startup creation. Register now at startupweekend.bt. Early bird registration ends February 15th.', 'Startup Weekend Bhutan', '2024-01-10', true),
('Loden Foundation Launches New Micro-lending Program', 'The Loden Foundation has announced a new micro-lending program specifically designed for women entrepreneurs in rural areas. The program offers loans up to Nu. 50,000 with competitive interest rates and mentorship support.', 'Loden Foundation', '2024-01-08', false),
('Bank of Bhutan Introduces Startup Loan Scheme', 'Bank of Bhutan has launched a new loan scheme for startups with simplified application processes and reduced collateral requirements. The scheme aims to support early-stage businesses with funding up to Nu. 2 million.', 'Bank of Bhutan', '2024-01-05', false),
('Royal University Research Collaboration with Tech Companies', 'The Royal University of Bhutan has announced new research collaborations with leading tech companies to promote innovation in artificial intelligence and sustainable technology solutions.', 'Royal University of Bhutan', '2023-12-20', false);