-- Continue adding organizations from spreadsheet data
-- Media Organizations
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('ChainZapper', 'Blockchain-focused startup in Bhutan', 'startups', '{"Blockchain", "Cryptocurrency", "Technology"}', '{"Blockchain Solutions", "Crypto Services", "Technology Development"}', '{"Crypto Enthusiasts", "Blockchain Developers", "Tech Community"}', 'Thimphu', 'https://chainzapper.com', 2020),
('SELLISE Digital Platforms', 'International digital platform company with Bhutan operations', 'startups', '{"Digital Platforms", "International", "Technology"}', '{"Digital Platform Development", "International Services", "Technology Solutions"}', '{"Businesses", "International Clients", "Digital Enterprises"}', 'Thimphu', 'https://sellise.ch', 2010),
('ScanCafe', 'Digital learning and processing services with international operations', 'startups', '{"Digital Services", "Learning", "International"}', '{"Digital Learning", "Processing Services", "International Operations"}', '{"Educational Institutions", "International Clients", "Digital Learners"}', 'Thimphu', 'https://scancafe.com', 2005),
('NSN Technologies', 'Private technology services company', 'startups', '{"Technology", "Private", "Services"}', '{"Technology Services", "Private Solutions", "Tech Support"}', '{"Businesses", "Tech Companies", "Private Clients"}', 'Thimphu', 'https://nsn.bt', 2015),
('Zheypo', 'Local tech startup with details available through direct contact', 'startups', '{"Technology", "Local", "Startup"}', '{"Tech Solutions", "Local Services", "Startup Innovation"}', '{"Local Businesses", "Tech Community", "Consumers"}', 'Thimphu', 'contact@zheypo.bt', 2018);

-- Training and Mentorship Organizations
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('UP Shift (UNICEF)', 'UNICEF-backed skills development program with international development focus', 'training', '{"UNICEF", "Skills Development", "International", "Youth"}', '{"Skills Development", "Youth Programs", "International Training"}', '{"Youth", "Students", "Emerging Professionals"}', 'Thimphu', 'https://upshift.unicef.org', 2018),
('Student Leadership Entrepreneurship Development Program', 'Youth development program partnered with VVOB for social impact focus', 'training', '{"Youth", "Leadership", "Entrepreneurship", "Social Impact"}', '{"Leadership Development", "Entrepreneurship Training", "Youth Programs"}', '{"Students", "Young Leaders", "Aspiring Entrepreneurs"}', 'Thimphu', 'https://www.vvob.org', 2019),
('Mentorship For Women Entrepreneurs (Cherie Blair Foundation)', 'Women-focused entrepreneurship mentorship with international and local partnerships', 'training', '{"Women", "Entrepreneurship", "Mentorship", "International"}', '{"Women Entrepreneurship", "Mentorship Programs", "Business Development"}', '{"Women Entrepreneurs", "Female Leaders", "Business Women"}', 'Thimphu', 'https://cherieblairfoundation.org', 2016),
('Business Coaching Program (Help for Thimphu)', 'Business coaching and mentorship services with local and global impact hub network', 'training', '{"Business Coaching", "Mentorship", "Global Network"}', '{"Business Coaching", "Mentorship Services", "Global Connections"}', '{"Business Owners", "Entrepreneurs", "SMEs"}', 'Thimphu', 'https://helpforthimphu.org', 2017),
('Youth-led AgriTech Innovation Challenge (FAO)', 'FAO-backed agricultural technology innovation program for blockchain supply chain solutions', 'training', '{"Youth", "AgriTech", "Innovation", "FAO", "Blockchain"}', '{"Agricultural Innovation", "Youth Programs", "Blockchain Training"}', '{"Young Farmers", "AgriTech Innovators", "Students"}', 'Thimphu', 'https://fao.org', 2020);

-- Big Business/Conglomerate
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Global Entrepreneur Week (DoEE MoICE)', 'International entrepreneurship event with government-backed global connections', 'events', '{"International", "Entrepreneurship", "Government", "Global"}', '{"Entrepreneurship Events", "Global Networking", "Government Support"}', '{"Entrepreneurs", "International Businesses", "Startups"}', 'Thimphu', 'contact@moice.gov.bt', 2015),
('World Entrepreneurship Day Event', 'International entrepreneurship day celebration with government-backed awareness events', 'events', '{"International", "Entrepreneurship", "Awareness", "Government"}', '{"Entrepreneurship Awareness", "International Events", "Community Building"}', '{"General Public", "Entrepreneurs", "Students"}', 'Thimphu', 'contact@entrepreneurs.bt', 2018),
('G-Tech (Gedu College of Business School)', 'University business festival supporting entrepreneurship and innovation focus', 'events', '{"University", "Business", "Festival", "Innovation"}', '{"Business Festival", "University Events", "Innovation Showcases"}', '{"University Students", "Business Community", "Young Entrepreneurs"}', 'Gedu', 'https://gcbs.edu.bt', 2012),
('National Library Weekend Startup Orientation Bootcamp', 'National library-based startup community building with grassroots entrepreneurship support', 'events', '{"Startup", "Community", "Library", "Grassroots"}', '{"Startup Orientation", "Community Building", "Entrepreneurship Support"}', '{"Aspiring Entrepreneurs", "Community Members", "Students"}', 'Thimphu', 'https://library.gov.bt', 2019),
('Friday Friends (iBhutan)', 'Regular networking event for tech and business community with informal networking', 'events', '{"Networking", "Tech", "Business", "Community"}', '{"Regular Networking", "Tech Community", "Business Connections"}', '{"Tech Professionals", "Business Community", "Entrepreneurs"}', 'Thimphu', 'https://ibhutan.bt', 2017);

-- Market Access Organizations
INSERT INTO public.organizations (name, description, category, tags, programs, target_audience, location, website, established) VALUES
('Tashi Group (Diversified Holdings)', 'Operates TashiCell and T-Bank with potential for blockchain integration in banking and telecom', 'market', '{"Conglomerate", "Banking", "Telecom", "Blockchain"}', '{"Banking Services", "Telecommunications", "Diversified Holdings"}', '{"Consumers", "Businesses", "Financial Clients"}', 'Thimphu', 'https://www.tashigroup.bt', 1960),
('Bhutan National Bank', 'Major commercial bank with potential customer Web3 and blockchain solutions', 'market', '{"Banking", "Commercial", "Web3", "Blockchain"}', '{"Commercial Banking", "Web3 Services", "Blockchain Solutions"}', '{"Businesses", "Individual Customers", "Financial Institutions"}', 'Thimphu', 'https://www.bnb.bt', 1997),
('Bank of Bhutan', 'Major commercial bank with potential customer Web3 and blockchain solutions', 'market', '{"Banking", "Commercial", "Web3", "Blockchain"}', '{"Commercial Banking", "Digital Solutions", "Financial Services"}', '{"Businesses", "Individual Customers", "Financial Institutions"}', 'Thimphu', 'https://www.bob.bt', 1968),
('Bhutan Telecom Limited', 'National telecom provider with potential for blockchain-based telecommunications services', 'market', '{"Telecommunications", "National Provider", "Blockchain"}', '{"Telecom Services", "Digital Infrastructure", "Blockchain Integration"}', '{"Consumers", "Businesses", "Government"}', 'Thimphu', 'https://www.bt.bt', 2000),
('Trade Shows (BCCI)', 'Trade promotion and market access facilitation with potential for blockchain-based trade verification', 'market', '{"Trade", "Market Access", "BCCI", "Blockchain"}', '{"Trade Promotion", "Market Access", "Trade Verification"}', '{"Traders", "Exporters", "Businesses"}', 'Thimphu', 'https://www.bcci.org.bt', 1980);